import {
  arAdultPdf,
  enAdultPdf,
  enChildPdf,
  enTeenagerPdf,
  esAdultPdf,
  frAdultPdf,
  frChildPdf,
  frTeenagerPdf,
  itAdultPdf,
  jaAdultPdf,
  plAdultPdf,
  ptAdultPdf,
  ruAdultPdf,
  zhAdultPdf,
} from 'assets/books';
import { Age } from 'enums/age';
import { Language } from 'enums/language';

type CompetitionTypes = {
  [key in Language]: {
    [key in Age]?: {
      start: Date;
      words?: number;
      book: string;
      questions: string[];
    };
  };
};

const competition: CompetitionTypes = {
  [Language.ZH]: {
    [Age.adult]: {
      start: new Date('Sun, 30 May 2021 14:00:00'),
      book: zhAdultPdf,
      questions: ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
    },
  },
  [Language.PL]: {
    [Age.adult]: {
      start: new Date('Sun, 30 May 2021 14:00:00'),
      words: 53771,
      book: plAdultPdf,
      questions: [
        'Kto nie wytrzymał nerwowo podczas akcji wykopywania ciał z grobów na cmentarzu?',
        'Od kogo Connor pożyczył pieniądze na kaucję Adriena i Steva Collinsa?',
        'Do kogo należała farma pod Bostonem, na którą pojechali agenci wraz z Mary i rabusiami i co się tam wydarzyło?',
        'Komu znajomy lekarz nastawił złamaną nogę?',
        'W jakich okolicznościach i w jakim miejscu  policjanci odnaleźli pierwszą kość która przypominała flet?',
        'Agent Perlman musiał przesłuchać czarnoskórego mężczyznę, który wpadł w panikę i nie chciał być zamknięty za kratkami. Z jakiego powodu?',
        'Jak nazywał się portowy bar, gdzie spotkali się przestępcy?',
        'Co się wydarzyło podczas kolacji Mary z jej rodzicami i jej narzeczonym?',
        'Kto jest najlepszym przyjacielem profesora Mikaelsena?',
        'Ile dolarów otrzymali przestępcy jako zaliczkę za zlecenie kradziezy ciał z kostnicy od profesora Michelsena?',
        'W jakich okolicznościach zostali złapani Collins i Adrien przez Policję?',
        'Kogo przesłuchiwał Reilly w barze?',
        'Jak zakończył się rytuał?',
        'W jakim stanie Collins i Adrien odnaleźli Boba w jego mieszkaniu i co następnie zrobili?',
        'Który agent brał udział w sekcji zwłok 3 czarnoskórych mężczyzn?',
        'Kogo zaatakowała bestia w magazynie i podrapała jego plecy swoimi szponami?',
        'W czyjej piwnicy miał miejsce rytuał?',
        'Jak się nazywa policjant Który strzelił pierwszy podczas nalotu policji na nielegalną wytwórnię alkoholu w West Roxbury?',
        'Dokąd uciekł doktor Fuller po tym jak zobaczył bestie w szpitalu?',
        'Kogo spotkał na cmentarzu McKaya i co jej powiedział?',
      ],
    },
  },
  [Language.EN]: {
    [Age.child]: {
      start: new Date('Sun, 30 May 2021 14:00:00'),
      book: enChildPdf,
      questions: [
        'Why does Mr. Mach keep the books at home instead of returning them to the library?',
        'How many people are in the library book club?',
        'which character often falls asleep?',
        'how long is Mr. Mach excluded from the library?',
        'On what occasion do the book club members need Mr. Mach to rejoin their book club?',
        "What kind of pasta came with the dish that contained the book that Kika ate at Mr. Mach's house?",
        "During what season does Mrs. Floris go to Mr. Mach's house to scold him?",
        'What does Mr. Mach often wear on his head?',
        'What animal is on the TV show?',
        'How many participants are there in the contest?',
        'What happens to Mr. Mach on the day of the contest?',
        'Why does this happen to him?',
      ],
    },
    [Age.teenager]: {
      start: new Date('Sun, 30 May 2021 14:00:00'),
      book: enTeenagerPdf,
      questions: [
        'Why did Elias agree to receive a pen pal in his home?',
        'What planet does the pen pal come from?',
        'What is the reaction of the parents when Elias tells them that they are going to welcome an alien pen pal into their home? alien pen pal in their home?',
        "What is the pen pal's first name?",
        "What is the particularity of the pen pal's skin?",
        'What school subject were the pupils in when the headmistress introduced the pen pal to the class on the first day? correspondent to the class on the first day?',
        'On the first day, what was the main dish in the canteen for the pupils of the school? the school?',
        'Since which class are Elias and Angelo enemies?',
        'Which game is organised by the class teacher to show how to have fun on earth?',
        "What school supplies have disappeared from the students' kits and lockers?",
        'Who actually stole their school supplies?',
        'What was the punishment for the thief?',
        'What gift does Elias give to his pen pal before returning to his planet?',
        "What is the name of the pen pal's sister? What is the nickname of the teacher of the teacher's nickname?",
        'What is the nickname of the class teacher?',
      ],
    },
    [Age.adult]: {
      start: new Date('Sun, 30 May 2021 14:00:00'),
      words: 64977,
      book: enAdultPdf,
      questions: [
        "Who couldn't keep his cool when digging up the bodies from the graves in the cemetery?",
        'Who did Connor borrow the money from to bail out Adrien and Steve?',
        'Who owned the farm near Boston where the agents went with Mary and the robbers and what happened there?',
        'Whose broken leg has been set by an acquaintance who is a doctor?',
        'Under what circumstances and where did the police find the first bone that resembled a flute?',
        'Constable Perlman had to interrogate a black man who panicked and did not want to be locked up behind bars. For what reason?',
        'What was the name of the bar in the harbor where the criminals met?',
        "What happened during Mary's dinner with her parents and fiancé Albert Smith?",
        "Who is Professor Mikaelsen's best friend?",
        'How much money did the criminals receive in advance from Professor Michelsen for his request to steal the bodies from the morgue?',
        'Under what circumstances were Collins and Adrien arrested by the police?',
        'Who was questioned by Reilly at the bar?',
        'How did the ritual organised by Michelsen end?',
        'In what state did Collins and Adrien find Bob in his flat and what did they do next?',
        'Which agent attended the autopsy of three black men?',
        'Who was attacked by the monster (that scratched his back with his claws) in the warehouse?',
        'Who owns the basement in which Michelsen performed the ritual?',
        'What is the name of the policeman who fired the first shot during a raid on an illegal alcohol factory in West Roxbury?',
        'Where did Dr. Fuller go after seeing the monster in the hospital?',
        'Who did McKaya meet at the cemetery and what did he say to that person?',
      ],
    },
  },
  [Language.FR]: {
    [Age.child]: {
      start: new Date('Sun, 30 May 2021 14:00:00'),
      book: frChildPdf,
      questions: [
        'Pourquoi M. Mach garde-t-il les livres chez lui au lieu de les rendre à la bibliothèque ?',
        'Combien de personnes y a-t-il dans le club de lecture de la bibliothèque ?',
        'quel personnage s’endort souvent ?',
        'combien de temps M. Mach est-il exclu de la bibliothèque ?',
        'À quelle occasion les membres du club de lecture ont-ils besoin que M. Mach réintègre leur club de lecture ?',
        'Quel genre de pâtes accompagnaient le plat qui contenait le livre qu’a mangé Kika chez M. Mach ?',
        'Durant quelle saison Mme Floris se rend chez M. Mach pour le gronder ?',
        'Que porte souvent Monsieur Mach sur sa tête ?',
        "Quel animal présente l'émission de télévision ?",
        'Combien y a-t-il de participants au concours ?',
        'Qu’arrive-t-il à M. Mach le jour du concours ?',
        'Pourquoi lui arrive-t-il une telle situation ?',
      ],
    },
    [Age.teenager]: {
      start: new Date('Sun, 30 May 2021 14:00:00'),
      book: frTeenagerPdf,
      questions: [
        'Pourquoi Elias a-t-il accepté de recevoir un correspondant chez lui ?',
        'De quelle planète le correspondant vient-il ?',
        "Quelle est la réaction des parents lorsque Elias leur annonce qu'ils vont accueillir un correspondant extraterrestre chez eux ?",
        'Quel est le prénom du correspondant ?',
        'Quelle est la particularité de la peau du correspondant ?',
        'Pendant quelle matière scolaire les élèves étaient-ils lorsque la directrice a présenté le correspondant à la classe le premier jour ?',
        "Au cours de la première journée, quel était le plat principal à la cantine pour les élèves de l'école ?",
        'Depuis quelle classe Elias et Angelo sont-ils des ennemis ?',
        "Quel jeu est organisé par le maître de la classe pour montrer comment on s'amuse sur terre ?",
        'Quelle fourniture scolaires a disparu des trousses et des casiers des élèves ?',
        'Qui a réellement volé ses fournitures scolaires ?',
        'Quelle fut la sanction pour le voleur ?',
        'Quel cadeau Elias offre-t-il à son correspondant avant ce retour sur sa planète ?',
        "Comment s'appelle la sœur du correspondant ?",
        'Quel est le surnom du professeur de la classe ?',
      ],
    },
    [Age.adult]: {
      start: new Date('Sun, 30 May 2021 14:00:00'),
      words: 68072,
      book: frAdultPdf,
      questions: [
        "Qui n'a pas pu tenir son sang-froid pendant l'opération de déterrement des corps des tombes dans le cimetière ?",
        "A qui Connor a-t-il emprunté l'argent pour la caution d'Adrien et Steve ?",
        "A qui appartenait la ferme près de Boston où les agents se sont rendus avec Mary et les voleurs et ce qui s'est passé là-bas ?",
        "A qui l'ami médecin a soigné une jambe cassée ?",
        'Dans quelles circonstances et à quel endroit la police a-t-elle trouvé le premier os qui ressemblait à une flûte ?',
        "L'agent Perlman a dû interroger un homme noir qui a paniqué et ne voulait pas être enfermé derrière des barreaux. Pour quelle raison ?",
        'Quel est le nom du bar du port où les criminels se sont rencontrés?',
        "Que s'est-il passé lors du dîner de Mary avec ses parents et son fiancé Albert Smith ?",
        'Qui est le meilleur ami du professeur Mikaelsen?',
        'Combien de dollars les criminels ont-ils reçu comme avance pour avoir demandé au professeur Michelsen de voler des corps à la morgue ?',
        'Dans quelles circonstances Collins et Adrien ont-ils été arrêtés par la police ?',
        'Qui Reilly interrogeait-il au bar ?',
        "Comment s'est terminé le rituel organisé par Michelsen dans les sous-sols d’une maison ?",
        "Dans quel état Collins et Adrien ont-ils trouvé Bob dans son appartement et qu'ont-ils fait ensuite ?",
        "Quel agent a assisté dans l'autopsie de trois hommes noirs ?",
        "Qui s'est fait attaquer par le monstre ( qui a griffé son dos avec ses griffes) dans l'entrepôt. ?",
        'A qui appartient le sous-sol dans lequel Michelsen a fait le rituel ?',
        "Quel est le nom du policier qui a tiré le premier lors d'une descente de police dans une fabrique d'alcool illégale à West Roxbury ?",
        "Où est allé le Dr Fuller après avoir vu le monstre à l'hôpital ?",
        "Qui McKay a rencontré au cimetière et ce qu'il lui a dit?",
      ],
    },
  },
  [Language.IT]: {
    [Age.adult]: {
      start: new Date('Sun, 30 May 2021 14:00:00'),
      words: 61923,
      book: itAdultPdf,
      questions: [
        "Chi non ha tenuto i nervi saldi durante l'azione di scavo dei corpi dalle tombe nel cimitero?",
        'Da chi ha preso in prestito i soldi Connor della cauzione per Adrien e Steve Collins?',
        'A chi apparteneva la fattoria vicino a Boston dove gli agenti andarono con Mary e i rapinatori e cosa successe lì?',
        'A chi ha sistemato la gamba rotta il medico di conoscenza?',
        'In quali circostanze e in quale luogo la polizia ha trovato il primo osso che assomigliava a un flauto?',
        "L'agente Perlman ha dovuto interrogare un uomo di colore che è stato preso dal panico e non voleva essere rinchiuso dietro le sbarre. Per quale motivo?",
        'Come si chiamava il bar del porto dove si incontravano i criminali?',
        'Cosa è successo alla cena di Mary con i suoi genitori e il suo fidanzato?',
        'Chi è il migliore amico del professor Mikaelsen?',
        "Quanti dollari hanno ricevuto i criminali dal professor Michelsen come anticipo per il furto di corpi dall'obitorio?",
        'In quali circostanze Collins e Adrien sono stati catturati dalla polizia?',
        'Chi stava interrogando Reilly al bar?',
        'Come è finito il rituale?',
        'In quale stato Collins e Adrien hanno trovato Bob nel suo appartamento e cosa hanno fatto dopo?',
        "Quale agente ha partecipato all'autopsia dei 3 uomini di colore?",
        'Chi è stato attaccato dalla bestia nel magazzino ed è stato graffiato sulla schiena dai suoi artigli?',
        'Nella cantina di chi si è svolto il rituale?',
        'Come si chiama il poliziotto che ha sparato per primo durante un raid della polizia in una fabbrica illegale di liquori a West Roxbury?',
        "Dove è scappato il dottor Fuller dopo aver visto la bestia nell'ospedale?",
        'Chi ha incontrato al cimitero McKay e cosa gli ha detto?',
      ],
    },
  },
  [Language.PT]: {
    [Age.adult]: {
      start: new Date('Sun, 30 May 2021 14:00:00'),
      book: ptAdultPdf,
      questions: ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
    },
  },
  [Language.ES]: {
    [Age.adult]: {
      start: new Date('Sun, 30 May 2021 14:00:00'),
      words: 66227,
      book: esAdultPdf,
      questions: ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
    },
  },
  [Language.JA]: {
    [Age.adult]: {
      start: new Date('Sun, 30 May 2021 14:00:00'),
      book: jaAdultPdf,
      questions: ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
    },
  },
  [Language.AR]: {
    [Age.adult]: {
      start: new Date('Sun, 30 May 2021 14:00:00'),
      book: arAdultPdf,
      questions: ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
    },
  },
  [Language.RU]: {
    [Age.adult]: {
      start: new Date('Sun, 30 May 2021 14:00:00'),
      book: ruAdultPdf,
      questions: ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
    },
  },
};

export { competition };
