export enum Browser {
  android = 'Android',
  blackBerry = 'BlackBerry',
  chrome = 'Chrome',
  edge = 'Edge',
  fireBird = 'Firebird',
  firefox = 'Firefox',
  iCab = 'iCab',
  iceCat = 'GNU IceCat',
  iceWeasel = 'GNU IceWeasel',
  internetExplorer = 'Internet Explorer',
  internetExplorerMobile = 'Internet Explorer Mobile',
  konqueror = 'Konqueror',
  lynx = 'Lynx',
  mozilla = 'Mozilla',
  msnTv = 'MSN TV',
  netscape = 'Netscape',
  nokia = 'Nokia Browser',
  opera = 'Opera',
  operaMini = 'Opera Mini',
  operaMobile = 'Opera Mobile',
  phoenix = 'Phoenix',
  safari = 'Safari',
  samsung = 'Samsung Internet',
  blackBerryTabletOs = 'BlackBerry Tablet OS',
  uc = 'UC Browser',
  unknown = 'unknown',
}
